/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 CubeFace.gltf --transform 
Files: CubeFace.gltf [1.66KB] > /Users/ajay/repo_primathon/centuryply-fe/public/CubeFace/CubeFace-transformed.glb [1.2KB] (28%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/CubeFace-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} position={[0, 49.1, 0]} scale={50} />
    </group>
  )
}

useGLTF.preload('/CubeFace-transformed.glb')
